# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dec095a7dabd2f188d9abf1cb525890502f803475f209489e076ced4c75e66b04da765982caa150fffdb17e1d14e5aa7c09bf2dcca392f7a1d788bbca5fee133

test:
  secret_key_base: 684e25d78e4b79da0f6780fa4e2d8c7d5e5282e97f9bc3203a08cee5f70fae77461345ca8489bea70cec781376fe8a1f9ca9c8a820712c7cabd5c8f7bd7c41e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
